#!/bin/bash

#
# liburing.h and liburing/*.h need to be in /usr/include
# liburing.a needs to be in /usr/lib
#

#CFLAGS='-Wall -O0 -g -fsanitize=address -fno-omit-frame-pointer -fsanitize-recover=address'
#CFLAGS='-g'
CFLAGS='-O3'

gcc -c mrloop.c -o mrloop.o ${CFLAGS}

if [ "$1" == "install" ]; then
  ar -x /usr/lib/liburing.a
  ar crs libmrloop.a mrloop.o *.ol
  rm *.ol
  mv libmrloop.a /usr/local/lib
  cp mrloop.h /usr/local/include
fi

